cleanup

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -106,6 +106,9 @@ jobs:
           if [ "$TAG_VERSION" = "null" ]; then
             TAG_VERSION="v0.0.0"
             FIRST_CATALOG_RUN=true
+          elif [ "$TAG_VERSION" = "latest" ]; then
+            echo "::error::'latest' tag pushed out of order.  remove 'latest' tag from operators_catalog and run again."
+            exit 1
           else
             FIRST_CATALOG_RUN=false
           fi
