fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,6 +21,14 @@ on:
         - major
         - minor
         - patch
+      pull_branch:
+        type: choice
+        description: Branch to deploy
+        required: true
+        default: 'aws'
+        options:
+        - aws
+        - azure
       first_run:
         type: choice
         description: Set to true only if first run
@@ -40,11 +48,13 @@ jobs:
 
       - name: Set inputs
         run: |
-          if [ {GITHUB_REF#refs/heads/} != "aws" ] && [ ${GITHUB_REF#refs/heads/} != "azure" ]; then
-            echo "::error::Branch must be 'aws' or 'azure'"
-            exit 1
-          else
+          if [ {GITHUB_REF#refs/heads/} == "main" ]; then
+            echo "BRANCH=$(echo ${{ inputs.pull_branch }})" >> $GITHUB_ENV
+          elif [ {GITHUB_REF#refs/heads/} == "aws" ] || [ ${GITHUB_REF#refs/heads/} == "azure" ]; then
             echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
+          else
+            echo "::error::Branch is not set to 'aws' or 'azure'"
+            exit 1
           fi
 
           if [ -z "${{ inputs.increment_devops_version }}" ]; then
@@ -70,6 +80,8 @@ jobs:
 
       - name: Checkout branch
         uses: actions/checkout@v3
+        with:
+          ref: $BRANCH
 
       - name: Set versions
         run: |
