aws

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,13 +21,6 @@ on:
         - major
         - minor
         - patch
-      cloud_provider:
-        type: choice
-        description: Used for branch and channel targeting
-        required: true
-        default: 'aws'
-        options:
-        - aws
       first_run:
         type: choice
         description: Set to true only if first run
@@ -45,17 +38,41 @@ jobs:
     timeout-minutes: 4
     steps:
 
-      - name: Log inputs
+      - name: Set inputs
         run: |
-          echo "::notice::increment_devops_version = ${{ inputs.increment_devops_version }}"
-          echo "::notice::increment_catalog_version = ${{ inputs.increment_catalog_version }}"
-          echo "::notice::cloud_provider = ${{ inputs.cloud_provider }}"
-          echo "::notice::first_run = ${{ inputs.first_run }}"
+          if ! [ ${GITHUB_REF#refs/heads/} == "aws" ] || [ ${GITHUB_REF#refs/heads/} == "azure" ]; then
+            echo "::error::Branch must be 'aws' or 'azure'"
+            exit 1
+          else
+            echo "CLOUD_PROVIDER=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
+          fi
+
+          if [ -z "${{ inputs.increment_devops_version }}" ]; then
+            echo "INCREMENT_DEVOPS_VERSION=patch" >> $GITHUB_ENV
+          else
+            echo "INCREMENT_DEVOPS_VERSION=$(echo ${{ inputs.increment_devops_version }})" >> $GITHUB_ENV
+          fi
+
+          if [ -z "${{ inputs.increment_catalog_version }}" ]; then
+            echo "INCREMENT_CATALOG_VERSION=patch" >> $GITHUB_ENV
+          else
+            echo "INCREMENT_CATALOG_VERSION=$(echo ${{ inputs.increment_catalog_version }})" >> $GITHUB_ENV
+          fi
+
+          if [ -z "${{ inputs.first_run }}" ]; then
+            echo "FIRST_RUN=false" >> $GITHUB_ENV
+          else
+            echo "FIRST_RUN=$(echo ${{ inputs.first_run }})" >> $GITHUB_ENV
+          fi
         shell: bash
 
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ inputs.cloud_provider }}
+      - name: Log inputs
+        run: |
+          echo "::notice::increment_devops_version = $INCREMENT_DEVOPS_VERSION"
+          echo "::notice::increment_catalog_version = $INCREMENT_CATALOG_VERSION"
+          echo "::notice::cloud_provider = $CLOUD_PROVIDER"
+          echo "::notice::first_run = $FIRST_RUN"
+        shell: bash
 
       - name: Set versions
         id: set_versions
@@ -77,7 +94,6 @@ jobs:
         shell: bash
         env:
           TOKEN: ${{ secrets.QUAY_API_TOKEN }}
-          CHANNEL: ${{ inputs.cloud_provider }}
 
       - name: Install Operator SDK
         run: |
@@ -233,7 +249,7 @@ jobs:
           echo "NAME: $NAME"
           yq -i eval '.metadata.name = "'$NAME'"' config/manifests/bases/devopsinabox.clusterserviceversion.yaml
 
-          make bundle CHANNELS=$CHANNEL DEFAULT_CHANNEL=$CHANNEL
+          make bundle CHANNELS=$CLOUD_PROVIDER DEFAULT_CHANNEL=$CLOUD_PROVIDER
           make docker-build docker-push
           make bundle-build
           docker push $BUNDLE_IMG
@@ -252,8 +268,4 @@ jobs:
           docker push $CATALOG_IMAGE_VERSION
         shell: bash
         env:
-          INCREMENT_DEVOPS_VERSION: ${{ inputs.increment_devops_version }}
-          INCREMENT_CATALOG_VERSION: ${{ inputs.increment_catalog_version }}
-          CHANNEL: ${{ inputs.cloud_provider }}
-          FIRST_RUN: ${{ inputs.first_run }}
           ORGANIZATION: shawn_stout_org
