aws fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -155,6 +155,14 @@ jobs:
 
       - name: Helm Check
         run: |
+          helm template devopsinabox-helm-chart --dry-run > /dev/null
+          if [ $? -eq 0 ]
+          then
+            echo "::notice::Helm template devopsinabox-helm-chart compiled successfully."
+          else
+            echo "::error::Helm template devopsinabox-helm-chart failed to compile."
+            exit 1
+          fi
 
           helm template devopsinabox-namespace-helm-chart --dry-run > /dev/null
           if [ $? -eq 0 ]
@@ -180,15 +188,6 @@ jobs:
             echo "::notice::Helm template dotnet-app-helm-chart compiled successfully."
           else
             echo "::error::Helm template dotnet-app-helm-chart failed to compile."
-            exit 1
-          fi
-
-          helm template devopsinabox-helm-chart --dry-run > /dev/null
-          if [ $? -eq 0 ]
-          then
-            echo "::notice::Helm template devopsinabox-helm-chart compiled successfully."
-          else
-            echo "::error::Helm template devopsinabox-helm-chart failed to compile."
             exit 1
           fi
         shell: bash
@@ -231,7 +230,7 @@ jobs:
             - "jobs"
           EOF
 
-          export VERSION=$(../scripts/tools/increment_version.sh $OLD_VERSION $INCREMENT_DEVOPS_VERSION)-$BRANCH
+          export VERSION=$(../tools/increment_version.sh $OLD_VERSION $INCREMENT_DEVOPS_VERSION)-$BRANCH
           export IMG=quay.io/$ORGANIZATION/devopsinabox-operator:v$VERSION
           export BUNDLE_IMG=quay.io/$ORGANIZATION/devopsinabox-operator-bundle:v$VERSION
 
@@ -261,7 +260,7 @@ jobs:
           make bundle-build
           docker push $BUNDLE_IMG
 
-          export CATALOG_VERSION=$(../scripts/tools/increment_version.sh $OLD_CATALOG_VERSION $INCREMENT_CATALOG_VERSION)
+          export CATALOG_VERSION=$(../tools/increment_version.sh $OLD_CATALOG_VERSION $INCREMENT_CATALOG_VERSION)
           export CATALOG_IMAGE_LATEST=quay.io/$ORGANIZATION/operators-catalog:latest
           export CATALOG_IMAGE_VERSION=quay.io/$ORGANIZATION/operators-catalog:v$CATALOG_VERSION
           if [[ $FIRST_RUN == false ]]
